export enum EService {
	Authentication = "Authentication",
	Authorization = "Authorization",
	Avalanche = "Avalanche",
	Collection = "Collection",
	CorporateGateway = "CorporateGateway",
	Corporate = "Corporate",
	CustomerGateway = "CustomerGateway",
	Fuji = "Fuji",
	Identity = "Identity",
	InternalGateway = "InternalGateway",
	IPFS = "IPFS",
	JumioGateway = "JumioGateway",
	Mumbai = "Mumbai",
	Notification = "Notification",
	Polygon = "Polygon",
	PublicGateway = "PublicGateway",
	ReferralLink = "ReferralLink",
	Rinkeby = "Rinkeby",
	TestChain = "TestChain",
	TestChain2 = "TestChain2",
	Token = "Token",
	UserGateway = "UserGateway",
}
